<a href="https://colab.research.google.com/github/towardsai/ai-tutor-rag-system/blob/main/notebooks/02-Basic_RAG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building a Basic RAG Pipeline From Scratch

In RAG 101 we did "retrieval" by hand — we pasted the right document into the prompt. In this notebook we automate it, **from scratch, in plain Python**: split articles into chunks, turn chunks into embedding vectors, find the chunks most similar to a question, and answer from them.

**This notebook is the template for the whole course.** Everything the rest of Part 1 does — vector databases, better chunking, hybrid search, reranking, evaluation — grows *this exact pipeline*, step by step, into the production AI Tutor. No framework hides the steps: every moving part is a few lines of code you can read.

## 🧭 What You'll Learn

- The four moves of every RAG pipeline: **chunk → embed → search → answer**
- The course-standard **`embed()` helper** (Gemini embeddings by default, OpenAI as the alternative) — new in this notebook, reused for the rest of the course
- Why documents and questions **must** go through the same embedding model, and how a mismatch silently destroys retrieval
- How cosine similarity turns "meaning" into a number you can sort by
- Top-k retrieval, and how to *look at* retrieved chunks and scores before trusting them
- Grounded generation with the course augmentation template — plus the private-fact demo showing why grounding matters

## 1. Setup: Environment, Keys, and Providers

The standard setup cell, now with a second dropdown: `EMBED_PROVIDER`. Chat and embeddings are independent choices — the course default is Gemini for both. (Anthropic has no embedding API, so embeddings offer Gemini or OpenAI.)

The **model fields are editable dropdowns** (`{allow-input: true}`): pick one of the listed course defaults, or type any newer model ID straight into the box — no code changes needed. (Locally, simply edit the string.)

⚠️ *If you change `EMBED_MODEL` after having already embedded the dataset, you must re-embed — vectors from two different embedding models are not comparable. The code below enforces this for you; Section 5 explains why it matters.*

In [1]:
# ============================================================
# ⚙️ Setup — environment, dependencies, API keys, provider
# ============================================================
import os
import sys

IN_COLAB = "google.colab" in sys.modules

# Pick your model providers (dropdowns in Colab; edit the values locally)
PROVIDER = "gemini"  # @param ["gemini", "openai", "anthropic"]
EMBED_PROVIDER = "gemini"  # @param ["gemini", "openai"]  (Anthropic has no embedding API)

# Pick a model for the selected provider — or TYPE any newer model ID into the
# box (the dropdown is editable thanks to allow-input):
CHAT_MODEL = "gemini-3.7-flash"  # @param ["gemini-3.7-flash", "gemini-3.5-flash-lite", "gpt-5.6-luna", "claude-sonnet-5"] {allow-input: true}
EMBED_MODEL = "gemini-embedding-001"  # @param ["gemini-embedding-001", "gemini-embedding-2", "text-embedding-3-small"] {allow-input: true}

_KEY_FOR = {"gemini": "GOOGLE_API_KEY", "openai": "OPENAI_API_KEY", "anthropic": "ANTHROPIC_API_KEY"}
REQUIRED_KEYS = sorted({_KEY_FOR[PROVIDER], _KEY_FOR[EMBED_PROVIDER]})

if IN_COLAB:
    import importlib
    import site
    import subprocess

    # Shared install profile, pinned course-wide (July 2026).
    subprocess.run(
        [
            sys.executable, "-m", "pip", "install", "-q", "-U",
            "google-genai==2.3.0",
            "openai==2.46.0",
            "anthropic==0.117.0",
        ],
        check=True,
    )
    importlib.reload(site)  # make newly installed packages importable without a runtime restart

    # In Colab: Secrets tab (🔑 icon) → Add new secret → e.g. GOOGLE_API_KEY
    from google.colab import userdata

    for key in REQUIRED_KEYS:
        os.environ[key] = userdata.get(key)

if not IN_COLAB:
    get_ipython().run_line_magic("load_ext", "autoreload")
    get_ipython().run_line_magic("autoreload", "2")

    # Locally: dependencies are installed once from the repo's requirements.
    # Keys live in a .env file at the repo root.
    from dotenv import load_dotenv

    load_dotenv()
    missing = [k for k in REQUIRED_KEYS if not os.getenv(k)]
    assert not missing, f"Missing from .env: {missing}"

print(f"✅ Setup complete — {'Colab' if IN_COLAB else 'local'} | chat: {PROVIDER} | embeddings: {EMBED_PROVIDER}")

✅ Setup complete — local | chat: gemini | embeddings: gemini


## 2. `generate()` and the New `embed()` Helper

`generate()` is unchanged from previous notebooks. **`embed()` is new** — and it is the second and last provider helper the course needs. It takes a list of texts and returns one vector per text; every option is configured to produce **1536-dimensional** vectors, so later notebooks can swap embedding providers without touching any other code.

The course default is **`gemini-embedding-001`**, and *why* is worth a minute, because it is the kind of judgement call you will make constantly. Google's current recommendation is the newer `gemini-embedding-2` — but that model is **multimodal**, and being multimodal changes its text API in ways that cost us something here:

| | `gemini-embedding-001` — course default | `gemini-embedding-2` — also selectable |
|---|---|---|
| Declaring the task | **A parameter**: `task_type="RETRIEVAL_DOCUMENT"` / `"RETRIEVAL_QUERY"` | **A text prefix**: `title: none \| text: ` / `task: search result \| query: ` |
| Getting one vector per text | Pass a plain list of strings | Wrap **each** input in its own `Content` object |
| Embedding our 388 chunks | 8 batched requests | up to 388, if the batch collapses |
| Price per 1M tokens | $0.15 | $0.20 |

This lesson embeds plain text and nothing else, so embedding-2's multimodal talent goes entirely unused — we would be paying more, sending more requests, and diverging from notebooks 03–06 in exchange for a capability we never call. **Newer is not automatically better; match the model to the job.**

`embed()` supports both, so switching is one dropdown away. The batching difference is the dangerous one and worth understanding even if you never switch: because `gemini-embedding-2` is multimodal, it reads a plain list in `contents` as **one document made of several parts** and returns a *single* aggregated vector — your whole corpus fused into one blurry average, with no error raised. So `embed()` wraps each input in its own `Content` object and then **checks that it got back as many vectors as it sent**, falling back to one call per input if not. Verify counts at API boundaries; never assume an API batched the way you meant.

⚠️ *`gemini-embedding-001` is already past its earliest announced shutdown date, so treat it as a model to migrate off rather than build on — the migration path is the dropdown above. Model IDs, prices, and behavior verified July 2026.*

In [2]:
# 📎 generate() was built in the "How To Use LLMs via API" notebook.
#    embed() is NEW in this notebook — and reused for the rest of the course.
from anthropic import Anthropic
from google import genai
from google.genai import types as genai_types
from openai import OpenAI

# Course-standard default models per provider (August 2026)
MODELS = {
    "gemini": "gemini-3.7-flash",
    "openai": "gpt-5.6-luna",
    "anthropic": "claude-sonnet-5",
}

# The setup-cell form selection (or any typed model ID) overrides the default:
MODELS[PROVIDER] = CHAT_MODEL
EMBED_MODELS = {
    "gemini": "gemini-embedding-001",
    "openai": "text-embedding-3-small",
}
EMBED_MODELS[EMBED_PROVIDER] = EMBED_MODEL  # setup-cell selection (or typed ID) wins
EMBED_DIM = 1536  # same output size for both providers, so the rest of the code never cares

# Create only the clients we actually need
if "gemini" in (PROVIDER, EMBED_PROVIDER):
    gemini_client = genai.Client()
if "openai" in (PROVIDER, EMBED_PROVIDER):
    openai_client = OpenAI()
if PROVIDER == "anthropic":
    anthropic_client = Anthropic()


def generate(prompt, system=None, model=None):
    """Send one prompt to the selected PROVIDER and return the reply text."""
    if PROVIDER == "gemini":
        response = gemini_client.models.generate_content(
            model=model or MODELS["gemini"],
            contents=prompt,
            config=genai_types.GenerateContentConfig(system_instruction=system),
        )
        return response.text

    if PROVIDER == "openai":
        response = openai_client.responses.create(
            model=model or MODELS["openai"],
            instructions=system,
            input=prompt,
            reasoning={"effort": "none"},
        )
        return response.output_text

    if PROVIDER == "anthropic":
        response = anthropic_client.messages.create(
            model=model or MODELS["anthropic"],
            max_tokens=4096,
            **({"system": system} if system else {}),
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text

    raise ValueError(f"Unknown PROVIDER: {PROVIDER!r}")


def embed(texts, task="document"):
    """Embed a list of texts with the selected EMBED_PROVIDER.

    Returns a list of EMBED_DIM-dimensional vectors (one per input text).
    task: "document" for corpus chunks, "query" for user questions. Retrieval
    models treat the two sides differently; see the table above for how each
    model family wants that declared.
    """
    if isinstance(texts, str):
        texts = [texts]
    # Embedding models work best on single-line inputs
    texts = [t.replace("\n", " ") for t in texts]

    if EMBED_PROVIDER == "gemini":
        model = EMBED_MODELS["gemini"]

        if model.startswith("gemini-embedding-2"):
            # Embedding 2 has no task_type: the task goes into the text as a prefix.
            # Documents carry a title slot ("none" when we have no title to give).
            prefix = "task: search result | query: " if task == "query" else "title: none | text: "
            payload = [prefix + t for t in texts]
            config = genai_types.EmbedContentConfig(output_dimensionality=EMBED_DIM)

            # Embedding 2 is multimodal: a plain list in `contents` is read as ONE
            # document of several parts and returns ONE aggregated vector. Each input
            # must be its own Content object to get one vector per input.
            result = gemini_client.models.embed_content(
                model=model,
                contents=[
                    genai_types.Content(parts=[genai_types.Part.from_text(text=t)])
                    for t in payload
                ],
                config=config,
            )
            vectors = [e.values for e in result.embeddings]

            # Trust nothing: if the batch still collapsed, embed one at a time.
            if len(vectors) != len(payload):
                vectors = [
                    gemini_client.models.embed_content(
                        model=model, contents=t, config=config
                    ).embeddings[0].values
                    for t in payload
                ]
            return vectors

        # Embedding 001 and earlier: an explicit task_type, and a plain list of
        # strings already returns one vector per string.
        result = gemini_client.models.embed_content(
            model=model,
            contents=texts,
            config=genai_types.EmbedContentConfig(
                task_type="RETRIEVAL_DOCUMENT" if task == "document" else "RETRIEVAL_QUERY",
                output_dimensionality=EMBED_DIM,
            ),
        )
        return [e.values for e in result.embeddings]

    if EMBED_PROVIDER == "openai":
        # dimensions= is redundant for text-embedding-3-small (1536 natively) but
        # keeps the 1536 contract if you type a different OpenAI model into the picker.
        result = openai_client.embeddings.create(
            model=EMBED_MODELS["openai"], input=texts, dimensions=EMBED_DIM
        )
        return [d.embedding for d in result.data]

    raise ValueError(f"Unknown EMBED_PROVIDER: {EMBED_PROVIDER!r}")

In [3]:
# Quick smoke test: one vector per input text. We assert the COUNT, not just the
# dimension — a batch that quietly returns fewer vectors than inputs is a real
# failure mode of embedding APIs, and it is silent until retrieval goes wrong.
vectors = embed(["LLMs predict tokens.", "What do LLMs predict?"])

assert len(vectors) == 2, f"Expected 2 vectors, got {len(vectors)} — the batch collapsed."
assert all(len(v) == EMBED_DIM for v in vectors), "Unexpected vector dimension."

print(f"Got {len(vectors)} vectors of dimension {len(vectors[0])}")

Got 2 vectors of dimension 1536


**What just happened?** An embedding model mapped each text to a point in 1536-dimensional space, where *similar meanings land near each other*. That single property powers the whole retrieval step: if a chunk's vector is close to the question's vector, the chunk is probably relevant. Everything else in this notebook is bookkeeping around that idea.

Note what the smoke test actually checked: **two inputs produced two vectors.** That sounds too obvious to test, until you meet a multimodal embedding model that helpfully fuses your list into one vector and returns it without complaint. Cheap assertions at API boundaries are how you find that in five seconds instead of three lessons later, staring at retrieval results wondering why every score looks the same.

## 3. Load the Dataset

Our corpus: **ai-docs**, a small CSV of 23 recent AI articles — 7 model cards, 8 release announcements, 8 technical explainers — the course's teaching corpus, hosted in the Towards AI org dataset repo on Hugging Face. It is a stand-in for the thousands of documentation pages the production tutor indexes. The download is plain Python, so it works identically in Colab and locally.

In [4]:
import pathlib
import requests

# Course dataset — hosted in the Towards AI org dataset repo on Hugging Face
DATA_URL = "https://huggingface.co/datasets/towardsai-tutors/full-stack-ai-engineering-data/resolve/main/ai-docs.csv"
DATA_PATH = pathlib.Path("ai-docs.csv")

if not DATA_PATH.exists():
    DATA_PATH.write_bytes(requests.get(DATA_URL, timeout=30).content)
    print("Downloaded", DATA_PATH)
else:
    print("Already present:", DATA_PATH)

Downloaded ai-docs.csv


## 4. Chunking: Splitting Articles into Retrieval-Sized Pieces

Whole articles are too big to embed and retrieve precisely, so we split them. Our first chunker is deliberately the simplest thing that works: fixed-size character windows, no overlap, no structure awareness.

⏭️ *Deliberately naive — two lessons from now we upgrade to token-based chunks with overlap, and later to the production heading-aware chunker (800 tokens, 100 overlap) that never splits a code block.*

In [5]:
# Split the input text into chunks of specified size.
def split_into_chunks(text, chunk_size=1024):
    chunks = []
    for i in range(0, len(text), chunk_size):
        chunks.append(text[i : i + chunk_size])
    return chunks

In [6]:
import csv

chunks = []

# Load the file as a CSV and chunk every article body (column 1)
with open(DATA_PATH, mode="r", encoding="utf-8") as file:
    csv_reader = csv.reader(file)
    for idx, row in enumerate(csv_reader):
        if idx == 0:
            continue  # skip the header row
        chunks.extend(split_into_chunks(row[1]))

print("number of articles:", idx)
print("number of chunks:", len(chunks))

number of articles: 23
number of chunks: 388


In [7]:
import pandas as pd

# Keep the chunks in a DataFrame — our tiny, in-memory "knowledge base"
df = pd.DataFrame(chunks, columns=["chunk"])
df.head(3)

,chunk
0,# Qwen3.8-2.4T-A95B\n\n## Qwen3.8 Highlights\n...
1,\n+ Number of Linear Attention Heads: 128 for ...
2,9.8 | 84.5 | 74.0 | 56.5 | 75.1 |\n| QwenSWEBe...


**What just happened?** A handful of articles became ~hundreds of chunks, each small enough to embed cheaply and retrieve precisely. Chunk boundaries currently fall mid-sentence without mercy — remember that when you inspect retrieval results later; it is exactly the weakness the later chunking lessons fix.

## 5. Embedding the Knowledge Base

Now we run every chunk through `embed()`. We batch requests (fewer API round-trips) and show progress. On the course's small dataset this costs a fraction of a cent — and Gemini's free tier typically covers it.

💡 *Re-running this cell re-bills you. Real pipelines embed once, store vectors, and reuse them — that's the vector-database lesson. Here we cache to a local CSV as a stopgap.*

⚠️ **The one rule of embedding caches: a cache belongs to exactly one model.** Vectors only mean anything relative to the model that produced them, so a cache written by model A is nonsense to a query embedded by model B — similarity scores collapse toward noise, retrieval returns unrelated chunks, and the model dutifully answers "no answer" from them. Nothing errors; the pipeline just quietly stops working. That failure has bitten this very lesson before, so the cache filename below carries the **model ID and dimension**, and the load path asserts the dimension matches. Change `EMBED_MODEL` and you simply get a different cache file — never a corrupted one.

In [8]:
# @title ⚙️ Embedding run { display-mode: "form" }
load_embedding = False  # @param {type:"boolean"}
# False → call the embedding API for every chunk (small cost)
# True  → load vectors from the cache file written by a previous run of this notebook

In [9]:
import numpy as np
from tqdm.auto import tqdm

# The cache key includes the MODEL and dimension, not just the provider: two
# embedding models produce incomparable vectors, so they must never share a file.
MODEL_TAG = EMBED_MODELS[EMBED_PROVIDER].replace("/", "-")
CACHE_PATH = pathlib.Path(f"ai-docs-embedded-{MODEL_TAG}-{EMBED_DIM}d.csv")
BATCH_SIZE = 50

if not load_embedding:
    print(f"Generating embeddings with {EMBED_MODELS[EMBED_PROVIDER]}...")
    embeddings = []
    for start in tqdm(range(0, len(df), BATCH_SIZE)):
        batch = df["chunk"].iloc[start : start + BATCH_SIZE].tolist()
        embeddings.extend(embed(batch, task="document"))
    assert len(embeddings) == len(df), (
        f"Got {len(embeddings)} vectors for {len(df)} chunks — the embedding batch "
        "collapsed; check the embed() batching branch for your model."
    )
    df["embedding"] = embeddings
    df.to_csv(CACHE_PATH, index=False)
    print("Cached embeddings to", CACHE_PATH)

else:
    import json

    assert CACHE_PATH.exists(), (
        f"No cache for {EMBED_MODELS[EMBED_PROVIDER]} at {CACHE_PATH}.\n"
        "Set load_embedding = False to build it (or switch EMBED_MODEL back to the "
        "model you embedded with)."
    )
    print("Loading cached embeddings from", CACHE_PATH)
    df = pd.read_csv(CACHE_PATH)
    # Stored vectors are JSON lists — parse with json.loads (never eval() on data!)
    df["embedding"] = df["embedding"].apply(lambda x: np.array(json.loads(x)))

# Guardrail: whatever we are about to search must be the same shape as the vector
# we will embed the question into. A silent mismatch here is the classic "no answer" bug.
cached_dim = len(df["embedding"].iloc[0])
assert cached_dim == EMBED_DIM, (
    f"Cached vectors are {cached_dim}-dim but EMBED_DIM is {EMBED_DIM} — "
    "re-embed with load_embedding = False."
)
print(f"✅ knowledge base: {len(df)} chunks × {cached_dim} dims, via {EMBED_MODELS[EMBED_PROVIDER]}")

Generating embeddings with gemini-embedding-001...


  0%|          | 0/8 [00:00<?, ?it/s]

Cached embeddings to ai-docs-embedded-gemini-embedding-001-1536d.csv
✅ knowledge base: 388 chunks × 1536 dims, via gemini-embedding-001


**What just happened?** Every chunk now has a 1536-dimensional vector sitting next to it, in a file named after the model that produced it — and an assertion confirming the shape before anything downstream depends on it. Two details in that cell are worth stealing for your own pipelines: the cache is keyed by model (so switching models can't corrupt retrieval, only cost you a re-embed), and stored vectors are parsed with `json.loads`. An earlier version of this notebook used `eval()` there — never do that: `eval()` executes whatever is in the file, so a poisoned cache file would run arbitrary code on your machine.

## 6. Embedding the Question

The question goes through the *same embedding model* as the chunks — that is the entire reason its vector is comparable to theirs. `embed()` handles the one difference for us: we pass `task="query"`, and it declares the query side however the selected model expects (an in-text prefix for `gemini-embedding-2`, a `task_type` parameter for `gemini-embedding-001`).

📎 *This is the same `embed()` call as Section 5, with one argument changed — which is exactly the point. When query-side and document-side embedding drift apart in a real system, it is almost never a dramatic bug; it is one config line, and the only symptom is answers quietly getting worse.*

In [10]:
QUESTION = "How many parameters does the Qwen3.8 model have?"

QUESTION_emb = np.array(embed(QUESTION, task="query")[0])
print(f"Question vector: {QUESTION_emb.shape}")

Question vector: (1536,)


## 7. Cosine Similarity: Meaning as a Number

Before searching the whole knowledge base, verify the core mechanism on two hand-made sentences: one that could answer the question and one that couldn't. Cosine similarity scores each against the question — higher means more similar in meaning.

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

BAD_SOURCE_emb = embed("The sky is blue.")[0]
GOOD_SOURCE_emb = embed("The Qwen3.8 model has a total of 3 billion parameters.")[0]

print("> Bad  Source Score:", cosine_similarity([QUESTION_emb], [BAD_SOURCE_emb])[0][0].round(4))
print("> Good Source Score:", cosine_similarity([QUESTION_emb], [GOOD_SOURCE_emb])[0][0].round(4))

> Bad  Source Score: 0.516
> Good Source Score: 0.8854


**What just happened?** The on-topic sentence should score far higher than the unrelated one — even though the "good" sentence's *fact* is wrong (Qwen3.8 isn't 3B; its model card says **2.4T total parameters, 95B activated**). Read that again: **similarity measures relatedness, not truth.** Retrieval finds text that *talks about* the right thing; whether the corpus is trustworthy is your data-curation problem (and why the knowledge-base lesson matters).

Look at the *absolute* numbers too, because they surprise people. "The sky is blue." — a sentence with nothing whatsoever to do with Qwen3.8 — will typically still land well above zero, not near 0.02. Cosine similarity on modern embedding models is a **ranking signal, not a probability**: each model has its own floor, its own spread, and its own idea of what 0.5 means. So never hard-code a threshold like `if score > 0.5: it's relevant` from a number you read in a tutorial. If you need a cutoff, measure the distribution on *your* corpus with *your* model — or better, use the evaluation harness we build in a few lessons and let the metric tell you.

## 8. Retrieval: Top-K Most Similar Chunks

Now score every chunk against the question, sort, and keep the best few. This is real retrieval — the same operation a vector database performs, minus the database.

In [12]:
NUM_CHUNKS_TO_RETRIEVE = 3

# Similarity between the question and every chunk in the knowledge base
cosine_similarities = cosine_similarity([QUESTION_emb], np.stack(df["embedding"].to_numpy()))[0]

# Indices of the top-k highest-scoring chunks
top_indices = np.argsort(cosine_similarities)[::-1][:NUM_CHUNKS_TO_RETRIEVE]

# Always LOOK at what you retrieved — chunks and scores — before trusting it
for rank, i in enumerate(top_indices, start=1):
    print(f"┌─ Rank {rank} | chunk #{i} | score {cosine_similarities[i]:.4f}")
    preview = df.chunk[i][:300].replace("\n", " ")
    print(f"│  {preview}...")
    print("└" + "─" * 60)

┌─ Rank 1 | chunk #0 | score 0.7774
│  # Qwen3.8-2.4T-A95B  ## Qwen3.8 Highlights  Qwen3.8 features the following enhancements:  - Core Capabilities: Comprehensive improvements across coding, professional work, research, and long-horizon agentic tasks. - Agent Execution: Stronger autonomous planning and better handling of environment fee...
└────────────────────────────────────────────────────────────
┌─ Rank 2 | chunk #1 | score 0.7515
│   + Number of Linear Attention Heads: 128 for V and 16 for QK + Head Dimension: 128 * Gated Attention: + Number of Attention Heads: 64 for Q and 4 for KV + Head Dimension: 256 + Rotary Position Embedding Dimension: 64 * Mixture of Experts: + Number of Experts: 512 + Number of Activated Experts: 10 Ro...
└────────────────────────────────────────────────────────────
┌─ Rank 3 | chunk #3 | score 0.7232
│  ) | 41.8 | 55.9 | 53.8 | 44.4 | 52.5 | | HealthBench | 52.4 | -- | 55.3 | 54.5 | 60.2 | | PLawBench | 69.6 | 70.2 | 72.3 | 58.9 | 73.2 | | PRBench-Lega

**What just happened?** One numpy call scored the entire knowledge base; `argsort` gave us the top-3. Inspecting the previews and scores is not optional ceremony — it is how you catch bad chunking, off-topic retrieval, and score cliffs *before* they turn into confident wrong answers downstream.

## 9. Augment and Generate

The finale: place the retrieved chunks into the course-standard augmentation template (the same one from RAG 101, with its explicit context boundaries) and let `generate()` answer *from them*.

In [13]:
SYSTEM_INSTRUCTION = (
    "You are an assistant and expert in answering questions from a chunks of content. "
    "Only answer AI-related question, else say that you cannot answer this question."
)

# Course-standard augmentation template: context inside explicit boundary tags.
PROMPT_TEMPLATE = (
    "Read the following informations that might contain the context you require to "
    "answer the question. You can use the informations starting from the "
    "<START_OF_CONTEXT> tag and end with the <END_OF_CONTEXT> tag. Here is the content:\n\n"
    "<START_OF_CONTEXT>\n{context}\n<END_OF_CONTEXT>\n\n"
    "Please provide an informative and accurate answer to the following question based "
    "on the available context. Be concise and take your time.\nQuestion: {question}\nAnswer:"
)

context = "".join(df.chunk[i] for i in top_indices)
formatted_prompt = PROMPT_TEMPLATE.format(context=context, question=QUESTION)

answer = generate(formatted_prompt, system=SYSTEM_INSTRUCTION)
print(answer)

Based on the provided context, the Qwen3.8 model has **2.4T (trillion) parameters in total**, with **95B (billion) activated parameters**.


**What just happened?** Chunk → embed → search → answer, end to end, in plain Python. The model answers from *our* articles, not from its training memory — the fact this question needs lives in the corpus's Qwen3.8-2.4T-A95B model card (**2.4T parameters in total, 95B activated**), so a correct grounded answer can be specific and sourced. This four-step loop is the skeleton of every RAG system you will ever build.

## 10. Why Grounding Matters: the Private-Fact Check

📎 *Same demo as RAG 101, now inside a real pipeline.* Ask about something no model was trained on — our AI Tutor's internal build notes — first **without** and then **with** the context. (These notes double as a map of where this pipeline is headed over the next lessons.)

In [14]:
# A "retrieved chunk" no public model has ever seen: the tutor's internal notes.
Example_chunk = """AI TUTOR — INTERNAL RELEASE NOTES (build 2026.07, codename "Cobalt")

Retrieval stack
- The chunker is heading-aware: it splits documents at Markdown headings into chunks of
  at most 800 tokens with a 100-token overlap, and it never splits a code block in half.
- Dense retrieval uses Gemini embeddings; lexical retrieval uses BM25. The two ranked
  lists are merged with Reciprocal Rank Fusion (RRF) before reranking.
- The fused candidates are reranked with a Cohere reranker; the final prompt receives
  only the top-scoring chunks.

Answering
- Every answer must cite the source chunks it used. If retrieval confidence is low, the
  tutor answers "I don't know" instead of guessing.
- Answer generation runs behind a single generate() helper, so any of the three major
  model providers can serve as the answering model per deployment."""

private_question = (
    "In the AI Tutor project's retrieval stack, what chunk size and overlap does the "
    "heading-aware chunker use, and how are the dense and lexical result lists combined?"
)

# --- Without augmentation: the model is on its own ---
print("WITHOUT CONTEXT:\n")
print(generate(
    f"Be concise and take your time to answer the following question.\nQuestion: {private_question}\nAnswer:",
    system="You are an assistant and expert in answering questions.",
))

WITHOUT CONTEXT:



In the AI Tutor project's retrieval stack:

* **Chunk Size and Overlap:** The heading-aware chunker typically uses a chunk size of **1,000 tokens** (or characters, depending on configuration) with an overlap of **200 tokens**.
* **Combining Results:** The dense (vector/semantic) and lexical (BM25/keyword) result lists are combined using **Reciprocal Rank Fusion (RRF)** (often followed by a cross-encoder reranker to produce the final ordering).


In [15]:
# --- With augmentation: same question, grounded in the notes ---
print("WITH CONTEXT:\n")
print(generate(
    PROMPT_TEMPLATE.format(context=Example_chunk, question=private_question),
    system=SYSTEM_INSTRUCTION,
))

WITH CONTEXT:



Based on the provided context:

* **Chunk size and overlap:** The heading-aware chunker creates chunks of **at most 800 tokens** with a **100-token overlap**.
* **Combining result lists:** The dense (Gemini embeddings) and lexical (BM25) ranked lists are merged using **Reciprocal Rank Fusion (RRF)** before reranking.


**What just happened?** Compare the two answers carefully, because the first one is the more instructive.

**Without context, the model did not say "I don't know" — it invented an answer.** In our July 2026 capture it presented "standard architectures for the AI Tutor retrieval stack" as if it knew ours: a "typical" **512-token** chunk size (the notes say 800) and a hedged **50–100 token** overlap range that happens to bracket the real 100. It even named Reciprocal Rank Fusion — correctly, but only because RRF is the industry default for hybrid retrieval, not because it has seen these notes. That mix is the trap in miniature: wrong specifics, hedged ranges, and lucky generic guesses, all delivered in the same confident format — and nothing in the response tells you which is which. Plausible-sounding specifics are what a language model produces when a question is well-formed and the knowledge is absent. (**Your output may differ** — some models refuse honestly instead. The refusal is the *lucky* outcome; fabrication is the dangerous one, and it is the one you should assume.)

**With context it answers precisely:** 800-token chunks, 100-token overlap, BM25 + dense lists fused with RRF — stated as facts from the notes, no "typically" anywhere. Same model, same question, one difference — the documents were in the prompt.

That contrast is the entire argument for RAG in one cell. And notice what those notes describe: heading-aware chunking, hybrid search, reranking, cited answers — **the upgrades this very pipeline receives over the rest of Part 1.** You just read the roadmap.

## 🔑 Key Takeaways

- A complete RAG pipeline is four moves — **chunk → embed → search → answer** — and fits in a screenful of plain Python. This script is the seed the rest of Part 1 grows into the production tutor.
- `embed()` joins `generate()` as the course's two provider helpers: Gemini embeddings by default, OpenAI as the drop-in alternative, everything at 1536 dimensions.
- **Documents and queries must be embedded by the same model.** Key caches by model ID, assert dimensions before you search, and re-embed when you switch — a mismatch produces no error, just steadily wrong retrieval and "no answer" replies.
- **Newer is not automatically better.** The current recommendation was multimodal, unbatchable for text, and pricier, while this lesson embeds nothing but text — so the previous generation was the right default. Match the model to the job.
- Read the embedding API you are actually calling. `gemini-embedding-2` takes its task as a text prefix and needs each input wrapped in its own `Content` object; `gemini-embedding-001` takes a `task_type` parameter and batches a plain list. Same concept, incompatible call sites.
- **Assert counts at API boundaries.** A multimodal embedding model will happily fuse a list of texts into one vector and return it without an error — check that N inputs gave you N vectors before anything downstream depends on it.
- Cosine similarity ranks by *relatedness, not truth* — retrieval quality is bounded by corpus quality and chunking quality.
- Always inspect retrieved chunks and scores; every later improvement (better chunking, hybrid search, reranking) exists because of failures you can see right here.
- Parse stored data with `json.loads`; `eval()` on file contents is a security hole.
- Grounding turns "the model doesn't know" into "the model answers from your documents" — and lets it honestly refuse when the documents don't cover the question.