<a href="https://colab.research.google.com/github/towardsai/ai-tutor-rag-system/blob/main/notebooks/13-Adding_Router.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Adding Question Validation and Routing

A RAG pipeline treats every question the same way: retrieve, augment, answer. Real questions are not the same. Some belong in the course knowledge base, some in a different corpus entirely, some deserve a specific (cheaper, or stronger) model — and some should be politely refused. **Routing** is the technique that makes those decisions explicit, and it is nothing more than one typed LLM call followed by an `if`/`else` you can read.

📎 *This is Section 9's first notebook — and the first to **import** the course toolkit, `tai-aitutor`: the `generate()`, `embed()`, `chunk()`, `search()`, and prompt-building you built by hand across Sections 3–7, packaged so the rest of the course stops copy-pasting them. The rule that governs it: a function lives in the package only if you wrote its identical twin by hand in Sections 1–8 — everything else stays written out in the notebook. It is deliberately not a framework: every function is a few dozen readable lines, and the 📎 notes below say which earlier lesson built each one.*

## 🧭 What You'll Learn

- Why later notebooks **import** the pipeline instead of re-pasting it — and what `tai-aitutor` is (and deliberately isn't)
- Loading the course's **prebuilt vector store** (7,428 chunks, embedded once) instead of re-embedding the corpus
- **Routing = one typed classification call** (`route()`) plus a plain `if`/`else` — no router engine, no selector classes
- Question **validation** as a route: the "reject" branch that keeps the tutor on-topic
- Building a second knowledge base (the **ai-docs** article set) with the chunk → embed → upsert loop written out
- Model routing: code questions to one model, everything else to the cheap default

## 1. Setup: Environment, Keys, and the Course Toolkit

One setup cell installs **`tai-aitutor`** (exact-pinned, `==0.0.3`) plus the pinned SDK profile, loads your keys, and picks the models. The **model fields are editable dropdowns** — choose a listed default or type any newer model ID. (Locally, edit the string.)

`tai-aitutor` is our own package: the helpers you wrote in earlier lessons, moved out of the notebooks and into a library we own. `setup_notebook()` is its environment half — keys from Colab Secrets (🔑 icon) in Colab or from `.env` locally, failing loudly with a fix-it message if one is missing — and `configure()` replaces the per-notebook `MODELS`/`EMBED_MODELS` dicts with one call.

In [1]:
# ============================================================
# ⚙️ Setup — environment, dependencies, API keys, provider
# ============================================================
import os
import sys

IN_COLAB = "google.colab" in sys.modules

# Pick your model providers (dropdowns in Colab; edit the values locally)
PROVIDER = "gemini"  # @param ["gemini", "openai", "anthropic"]
EMBED_PROVIDER = "gemini"  # @param ["gemini", "openai"]  (Anthropic has no embedding API)

# Pick a model for the selected provider — or TYPE any newer model ID into the
# box (the dropdown is editable thanks to allow-input):
CHAT_MODEL = "gemini-3.8-flash"  # @param ["gemini-3.8-flash", "gemini-3.5-flash-lite", "gpt-5.6-luna", "claude-sonnet-5"] {allow-input: true}
EMBED_MODEL = "gemini-embedding-001"  # @param ["gemini-embedding-001", "text-embedding-3-small"] {allow-input: true}

_KEY_FOR = {"gemini": "GOOGLE_API_KEY", "openai": "OPENAI_API_KEY", "anthropic": "ANTHROPIC_API_KEY"}
REQUIRED_KEYS = sorted({_KEY_FOR[PROVIDER], _KEY_FOR[EMBED_PROVIDER]})

if IN_COLAB:
    import importlib
    import site
    import subprocess

    # The course toolkit (exact-pinned) + the shared SDK profile (July 2026).
    subprocess.run(
        [
            sys.executable, "-m", "pip", "install", "-q", "-U",
            "tai-aitutor[gemini,openai,anthropic,rag]==0.0.3",
            "google-genai==2.3.0",
            "openai==2.46.0",
            "anthropic==0.117.0",
            "chromadb==1.5.9",
            "tiktoken==0.13.0",
        ],
        check=True,
    )
    importlib.reload(site)  # make newly installed packages importable without a runtime restart

if not IN_COLAB:
    get_ipython().run_line_magic("load_ext", "autoreload")
    get_ipython().run_line_magic("autoreload", "2")
    # Locally: install once into your venv —
    #   pip install "tai-aitutor[gemini,openai,anthropic,rag]==0.0.3"
    # Keys live in a .env file at the repo root.

from tai_aitutor import configure, setup_notebook

setup_notebook(required_keys=REQUIRED_KEYS)

# configure() sets the chat provider, the embedding provider, and the exact model
# IDs used by every toolkit function below. Passing the models explicitly keeps
# this notebook on the course-standard August 2026 models regardless of the
# package's own defaults.
cfg = configure(
    provider=PROVIDER,
    chat_model=CHAT_MODEL,
    embed_provider=EMBED_PROVIDER,
    embed_model=EMBED_MODEL,
)

print(f"✅ Setup complete — {'Colab' if IN_COLAB else 'local'} | {cfg}")

✅ Setup complete — local | Config(provider='gemini', chat_model='gemini-3.8-flash', embed_provider='gemini', embed_model='gemini-embedding-001')


## 2. The Pipeline, in One Import

Everything below was built by hand in an earlier lesson — the 📎 notes say which. Nothing here is new machinery except `route()`, which is this lesson's subject. (Read any of them with `??` — e.g. `route??` — the package is meant to be read, not trusted blindly.)

In [2]:
from tai_aitutor import (
    EMBED_DIM,         # 📎 the toolkit's fixed embedding width (1536)
    build_rag_prompt,  # 📎 "From Script to Pipeline" — the RAG prompt, visible
    chunk_document,    # 📎 chunking with stable, zero-padded chunk ids
    embed,             # 📎 "Basic RAG" — text in, 1536-wide vectors out
    generate,          # 📎 "How To Use LLMs via API" — one prompt in, one reply out
    get_collection,    # 📎 "Using a Vector Database" — Chroma, no wrapper
    load_csv,          # 📎 Section 6 — the one loader the toolkit keeps
    route,             # NEW this lesson — routing as ONE typed LLM call
    search,            # 📎 dense retrieval, with scores and metadata
    show_answer,
    show_chunks,
)

print("Toolkit ready.")

Toolkit ready.


## 3. Knowledge Base 1: the AI-Tutor Corpus, Prebuilt

📎 *Same corpus as "More Input Context" (Section 7): **`ai_tutor_knowledge`**, 788 documents of framework and tool documentation. The corpus was embedded **once** and published as prebuilt Chroma stores (zipped with a `manifest.json` recording exactly how they were built), so notebooks **load** the store instead of re-embedding 788 documents every runtime. The download stays in the notebook — the toolkit loads what you hand it; the course decides where data lives.*

Two details worth knowing before the cell below runs:

- **Dimensions.** The toolkit's `embed()` always produces `EMBED_DIM`-wide (1536) vectors, so we load the 1536-dimension store matching your `EMBED_PROVIDER`. (The 3072-dimension Gemini store in the same repo is for pipelines that embed at Gemini's native width, like Section 7's hand-written ones.)
- **Ids.** The store was built with `{doc_id}-{chunk_index}` chunk ids — the hand-written Section 7 scheme. The toolkit's `chunk_document()` writes zero-padded ids (`{doc_id}-0000`), and two id schemes must never share a collection (every chunk would be stored twice). That's fine here: we only *read* this store, and the store we build ourselves below gets its own collection.

In [3]:
import json
import pathlib
import shutil
import zipfile

import requests

# One prebuilt store per embedding provider — same corpus, same 512/128 chunking,
# only the embedding configuration differs. The toolkit embeds queries at
# EMBED_DIM (1536), so Section 9 loads the matching 1536-dimension store.
STORE_BASE = "https://huggingface.co/datasets/towardsai-tutors/full-stack-ai-engineering-data/resolve/main/vector_stores/"
STORE_FOR = {
    "gemini": "ai_tutor_knowledge-gemini-embedding-001-1536d-norm",
    "openai": "ai_tutor_knowledge-text-embedding-3-small-1536d",
}
DATASET_SHA = "0e801a3f"  # ties each store zip to the exact corpus file it was built from

slug = STORE_FOR[EMBED_PROVIDER]
zip_path = pathlib.Path(f"{slug}-{DATASET_SHA}.zip")
store_dir = pathlib.Path("prebuilt_stores") / slug

if not zip_path.exists():
    print(f"Downloading {zip_path.name} (~100 MB, one time)…")
    with requests.get(STORE_BASE + zip_path.name, stream=True, timeout=600) as response:
        response.raise_for_status()
        with open(zip_path, "wb") as f:
            shutil.copyfileobj(response.raw, f)

if not store_dir.exists():  # extract once; the Section 9 notebooks share this folder
    store_dir.parent.mkdir(exist_ok=True)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(store_dir.parent)

manifest = json.loads((store_dir / "manifest.json").read_text())

# 📎 get_collection(): the same call that creates a store also OPENS this one.
col_course = get_collection(manifest["collection_name"], path=str(store_dir / "chroma"))

# Trust, but verify: the manifest is the store's claim, written down.
assert col_course.count() == manifest["counts"]["chunks"], "chunk count ≠ manifest"
assert manifest["dimensions"]["actual"] == EMBED_DIM, "store width ≠ the toolkit's EMBED_DIM"

print(f"Prebuilt store ready: {col_course.count():,} chunks from "
      f"{manifest['source_dataset']['documents']} documents | "
      f"{manifest['embedding_model']} @ {manifest['dimensions']['actual']}d")

Prebuilt store ready: 7,428 chunks from 788 documents | gemini-embedding-001 @ 1536d


In [4]:
# Always LOOK at retrieval before building routing on top of it.
show_chunks(search("How does Retrieval Augmented Generation work?", col_course, top_k=3), max_chars=150)

**1. Lesson 9: Retrieval-Augmented Generation (RAG)** — score `0.805`

>  RAG system. Its primary job is to take a user's query and efficiently find the most relevant information from your knowledge base [[4]](https://towar…

**2. Lesson 9: Retrieval-Augmented Generation (RAG)** — score `0.793`

> , and clear instructions for the LLM on how to use that context to generate an accurate answer [[4]](https://towardsai.net/p/l/a-complete-guide-to-rag…

**3. Lesson 9: Retrieval-Augmented Generation (RAG)** — score `0.786`

> ]](https://decodingml.substack.com/p/rag-fundamentals-first?utm_source=publication-search).  After splitting, we pass each chunk to an embedding model…


In [5]:
# 📎 The full pipeline, written out — three toolkit calls composed in plain sight.
#    This is what the old framework hid inside a "query engine" object, and the
#    composition stays in the notebook on purpose: the toolkit keeps the stages,
#    you keep the chain.
def rag_answer(question, collection, top_k=3, **model_overrides):
    """Retrieve → prompt → generate. Overrides (model=, provider=) go to generate()."""
    hits = search(question, collection, top_k=top_k)
    reply = generate(build_rag_prompt(question, hits), **model_overrides)
    return reply, hits


reply, hits = rag_answer("How does Retrieval Augmented Generation (RAG) work?", col_course)
show_answer(reply, hits)

Based on the provided excerpts, Retrieval-Augmented Generation (RAG) works through three core components—**Retrieval**, **Augmentation**, and **Generation**—operating across two distinct operational phases:

---

### 1. Offline Ingestion & Indexing (Data Preparation)
Before handling live queries, the system prepares its knowledge base:
* **Loading:** Documents are gathered from sources such as PDFs, websites, or databases.
* **Splitting:** Documents are split into smaller, manageable chunks (such as single logical units or paragraphs) to fit LLM context limits and optimize retrieval precision.
* **Embedding:** An embedding model converts each text chunk into a dense numerical vector that captures its semantic meaning.
* **Storing:** The embeddings and their corresponding text chunks are stored in a specialized vector database (e.g., FAISS, Milvus, Qdrant, Pinecone) to create a searchable index.

---

### 2. Online Retrieval & Generation (Handling User Queries)
When a user asks a question, the system answers it in real time:
* **Retrieval:** 
  * The user's query is converted into a vector using the same embedding model used during ingestion.
  * The system performs semantic search by comparing the query vector against stored document vectors (often using metrics like cosine similarity) to find the top-$k$ most semantically relevant chunks.
* **Augmentation:** 
  * The retrieved document chunks are formatted into a structured prompt alongside the original query and clear instructions guiding the LLM on how to use that context.
* **Generation:** 
  * The augmented prompt is sent to the LLM. 
  * The model synthesizes the information to generate a coherent, factually grounded answer based on the provided context.

**Sources**

- **[1]** [Lesson 9: Retrieval-Augmented Generation (RAG)](https://academy.towardsai.net/courses/take/agent-engineering/multimedia/68380819-lesson-9-rag-focus) — `0.818` —  RAG system. Its primary job is to take a user's query and efficiently find the most relevant information from your knowledge base [[4]](https://towardsai.net/p…
- **[2]** [Lesson 9: Retrieval-Augmented Generation (RAG)](https://academy.towardsai.net/courses/take/agent-engineering/multimedia/68380819-lesson-9-rag-focus) — `0.802` — , and clear instructions for the LLM on how to use that context to generate an accurate answer [[4]](https://towardsai.net/p/l/a-complete-guide-to-rag).  Finall…
- **[3]** [Lesson 9: Retrieval-Augmented Generation (RAG)](https://academy.towardsai.net/courses/take/agent-engineering/multimedia/68380819-lesson-9-rag-focus) — `0.798` — ]](https://decodingml.substack.com/p/rag-fundamentals-first?utm_source=publication-search).  After splitting, we pass each chunk to an embedding model to **embe…

**What just happened?** The Section 7 pipeline ran again — as three imported calls composed in one visible function. Note the division of labour: `search()`, `build_rag_prompt()`, and `generate()` each have an inline twin you wrote by hand, so they live in the toolkit; the *composition* is four lines, so it lives here, where you can read and change it. And the store held 7,428 pre-embedded chunks — loading it took seconds where re-embedding 788 documents costs minutes and money.

## 4. Knowledge Base 2: the ai-docs Article Set

A router needs somewhere to route *to*. Our second corpus is deliberately different in kind from the course material: **ai-docs**, the course's set of 23 current AI articles — model cards, release announcements, and technical explainers — hosted in the same Towards AI org dataset. `load_csv()` reads it straight from the Hub URL, and this time we run the **chunk → embed → upsert loop written out** — the same three visible steps the indexing lesson taught. At 23 documents this takes seconds and a fraction of a cent; the prebuilt store above exists because the 788-document corpus does not share that luxury.

In [6]:
# The course's ai-docs set: 23 current articles — 7 model cards, 8 release
# announcements, 8 technical explainers.
AI_DOCS_URL = "https://huggingface.co/datasets/towardsai-tutors/full-stack-ai-engineering-data/resolve/main/ai-docs.csv"

# 📎 load_csv(): text from "content"; title/url/source ride along as metadata;
#    id_col="title" keeps chunk ids readable.
ai_docs = load_csv(AI_DOCS_URL, text_col="content", meta_cols=("title", "url", "source"), id_col="title")
print(f"{len(ai_docs)} documents | first: {ai_docs[0]}")

col_llm = get_collection("ai_docs", path="./tai-knowledge-chroma")

# The chunk → embed → upsert loop, written out — the toolkit deliberately ships
# no ingest() wrapper for it (📎 the indexing lesson's three visible steps):
chunks = [c for doc in ai_docs for c in chunk_document(doc)]
for start in range(0, len(chunks), 64):  # batch the embedding calls
    batch = chunks[start : start + 64]
    col_llm.upsert(
        ids=[c.id for c in batch],
        documents=[c.text for c in batch],
        embeddings=embed([c.text for c in batch]),
        metadatas=[c.metadata for c in batch],
    )
print(f"{col_llm.count()} chunks in '{col_llm.name}' — re-running upserts the same ids, no duplicates")

show_chunks(search("What's new in the latest Gemini Flash release?", col_llm, top_k=2), max_chars=150)

23 documents | first: Document(id='Qwen3.8-2.4T-A95B Model Card', 5572 chars, '# Qwen3.8-2.4T-A95B  ## Qwen3.8 Highlights  Qwen3.8 features'...)


233 chunks in 'ai_docs' — re-running upserts the same ids, no duplicates


**1. Introducing Gemini 3.6 Flash, 3.5 Flash-Lite, and 3.5 Flash Cyber** — score `0.756`

> 3.6 Flash builds directly on developer and customer feedback from 3.5 Flash. 3.6 Flash not only delivers a step up in coding and knowledge work, but i…

**2. Introducing Gemini 3.6 Flash, 3.5 Flash-Lite, and 3.5 Flash Cyber** — score `0.749`

> real-world task execution as seen in GDPval-AA v2 (1140 vs. 642).  In fact, on many agentic and coding evals, 3.5 Flash-Lite even outperforms 3 Flash,…


## 5. Routing: One Typed Call, Then `if`/`else`

The old framework version of this lesson wired a `RouterQueryEngine` with selector classes around "query engine tools". Strip the wrapping away and a router is: **describe your routes, ask the model to pick one, validate the pick, dispatch.** `route()` is exactly that — one structured-output call returning a typed `RouteDecision`, guaranteed to be one of your route names (an unresolvable pick raises instead of mis-routing silently).

Route descriptions do the same job tool descriptions do for agents: the model chooses by reading them, so write them like you mean them. And note what the third route is — **question validation is just a route.** The production tutor's system prompt says "politely reject questions not related to AI"; here the same rule is an explicit, testable branch.

In [7]:
ROUTES = {
    "course_kb": (
        "Questions about general Generative AI concepts and techniques — RAG, "
        "fine-tuning, prompting, embeddings, evaluation — answerable from the "
        "AI-tutor course knowledge base."
    ),
    "llm_facts": (
        "Questions about specific LLM models and vendors — what a model can do, "
        "what was just released, how models compare: answerable from the ai-docs "
        "article set (model cards and release announcements for Gemini, GPT, "
        "Claude, DeepSeek, Qwen, Kimi and friends)."
    ),
    "reject": (
        "Anything off-topic for an AI course: cooking, travel, medical advice, "
        "homework unrelated to AI."
    ),
}

decision = route("What can the Kimi K3 model do?", routes=ROUTES)
print(decision.route, "—", decision.reason)

llm_facts — The question asks about the capabilities of a specific LLM model (Kimi K3), which is covered by the model documentation and announcements.


In [8]:
def routed_answer(question, top_k=3):
    """The whole pattern: one classification call, then plain-Python dispatch."""
    decision = route(question, routes=ROUTES)
    print(f"[route: {decision.route}] {decision.reason}")
    if decision.route == "course_kb":
        return rag_answer(question, col_course, top_k=top_k)[0]
    if decision.route == "llm_facts":
        return rag_answer(question, col_llm, top_k=top_k)[0]
    return (
        "I'm your AI-course tutor, so I'll pass on that one — "
        "ask me anything about LLMs or RAG!"
    )


for q in [
    "What's new in the latest Gemini Flash release?",
    "Explain parameter-efficient finetuning methods",
    "Write the recipe for a chocolate cake.",
]:
    print("═" * 72)
    print("Q:", q, "\n")
    print(routed_answer(q), "\n")

════════════════════════════════════════════════════════════════════════
Q: What's new in the latest Gemini Flash release? 



[route: llm_facts] The question asks about updates and new features in a specific model release, Gemini Flash, which fits the model release announcements in the llm_facts route.


Based on the provided excerpts, the latest Gemini Flash release introduces three new models:

### 1. Gemini 3.6 Flash
* **Efficiency and Cost:** Consumes 17% fewer output tokens than 3.5 Flash (up to 65% fewer on benchmarks like DeepSWE), requires fewer reasoning steps and tool calls, and is priced lower than 3.5 Flash at $1.50 per 1M input tokens and $7.50 per 1M output tokens.
* **Performance Gains:** 
  * Better coding precision with fewer unwanted edits/loops on DeepSWE (49% vs. 37%).
  * Improved ML research capabilities on MLE Bench (63.9% vs. 49.7%).
  * Enhanced computer use capabilities on OSWorld-Verified (83.0% vs. 78.4%), which is now available as a built-in client-side tool via the Gemini API and Gemini Enterprise.
  * Improved multimodal and knowledge work on GDPval-AA v2 (1421 vs. 1349).
* **Safety:** Features enhanced Frontier Safety safeguards against Chemical, Biological, Radiological, and Nuclear (CBRN) risks and cyber offense misuse, with higher jailbreak resistance

[route: course_kb] The question asks for an explanation of parameter-efficient fine-tuning methods, which is a core Generative AI fine-tuning concept.


Based on the provided context excerpts, there is no mention or explanation of **parameter-efficient fine-tuning** (PEFT) methods. 

The context only mentions general fine-tuning and lists methods such as supervised fine-tuning, vision fine-tuning, direct preference optimization (DPO), and reinforcement fine-tuning (RFT). 

════════════════════════════════════════════════════════════════════════
Q: Write the recipe for a chocolate cake. 



[route: reject] The request is about baking a cake, which is off-topic for an AI course.
I'm your AI-course tutor, so I'll pass on that one — ask me anything about LLMs or RAG! 



**What just happened?** Three questions, three routes — and the router's *reason* printed next to each pick, which is your first debugging tool when a question lands in the wrong branch (fix the descriptions, not the model). The chocolate cake never touched retrieval, never reached the main prompt, and cost one cheap classification call. That is validation working as designed: the cheapest possible "no".

📌 *Production callout: the live AI Tutor is this pattern grown up — one agent deciding between a retrieval tool and other tools, with question validation done as scope rules in its system prompt. You are about to build exactly that, in miniature.*

## 6. Where the Agent Formulation Went

`route()` decides *before* anything runs — one cheap, auditable call, exactly one branch. The inversion — handing the model both knowledge bases as **tools** and letting it decide *during* generation which to search, including both or neither — is a real pattern too: it is how the production tutor works (one agent choosing between a retrieval tool and other tools, with question validation as scope rules in its system prompt). But a tool-calling loop deserves to be **built**, not imported — the toolkit deliberately ships no agent loop, because a hidden `while` loop is the thing the agents lesson exists to reveal.

⏭️ *Section 11 builds exactly that: the hand-rolled Thought → Action → Observation loop first, then the same loop natively in all three provider APIs. And the workflow-patterns lesson (Section 11) teaches routing as one of the standard orchestration patterns — what you built here is its RAG-specific application. What you have now is the upfront half of the production design; Section 11 builds the in-flight half.*

## 7. Model Routing: the Right Model per Question

Routing can pick **models**, not just corpora: send code questions to a stronger model and everything else to the cheap course default. Same `route()` call — only the dispatch changes what it varies. `generate()` takes per-call `model=`/`provider=` overrides, `rag_answer()` passes them straight through, and they never touch the `configure()` defaults.

In [9]:
MODEL_ROUTES = {
    "code": "Code-related questions: implementations, debugging, API usage, 'write the code for…'.",
    "general": "Conceptual or theoretical questions where no code is required.",
}

# Any (provider, model) pair works per branch — these are the course standards.
# NOTE: the code branch calls OpenAI, so it needs OPENAI_API_KEY in your keys
# (or point it at your own provider's strongest model instead).
CODE_MODEL = {"provider": "openai", "model": "gpt-5.6-luna"}
GENERAL_MODEL = {}  # empty overrides = the configure() default (Gemini)


def model_routed_answer(question, top_k=3):
    decision = route(question, routes=MODEL_ROUTES)
    overrides = CODE_MODEL if decision.route == "code" else GENERAL_MODEL
    print(f"[route: {decision.route}] → {overrides or 'course default'}")
    return rag_answer(question, col_course, top_k=top_k, **overrides)


show_answer(*model_routed_answer("How do I fine-tune the LLama model? Write the code for it"))

[route: code] → {'provider': 'openai', 'model': 'gpt-5.6-luna'}


```python
from llama_index.finetuning import OpenAIFinetuneEngine

# JSONL file containing the function-calling fine-tuning examples
finetune_engine = OpenAIFinetuneEngine(
    "gpt-3.5-turbo",
    "llama2_citation_events.jsonl",
    # start_job_id="<start-job-id>",  # use this if a job already exists
    validate_json=False,  # JSON validation does not yet support function calling
)

# Start fine-tuning
finetune_engine.finetune()

# Inspect the current fine-tuning job
job = finetune_engine.get_current_job()
print(job)

# Load the fine-tuned model
ft_llm = finetune_engine.get_finetuned_model(temperature=0.3)
```

For a RAG pipeline, plug the fine-tuned model into a `VectorStoreIndex` query engine:

```python
from llama_index.core import VectorStoreIndex

vector_index = VectorStoreIndex(nodes=nodes)

query_engine = vector_index.as_query_engine(
    output_cls=Response,
    similarity_top_k=1,
    llm=ft_llm,
)

query_str = "Which citation is used to measure the truthfulness of Llama 2?"

response = query_engine.query(query_str)
print(str(response))

# View the retrieved source
print(response.source_nodes[0].get_content())
```

The fine-tuning examples are stored in a JSONL file such as:

```python
finetuning_handler.save_finetuning_events(
    "llama2_citation_events.jsonl"
)
```

You can also fine-tune using a mock structured-output dataset:

```python
finetune_engine = OpenAIFinetuneEngine(
    "gpt-3.5-turbo",
    "mock_finetune_songs.jsonl",
    validate_json=False,
)

finetune_engine.finetune()

ft_llm = finetune_engine.get_finetuned_model(temperature=0.3)
```

**Sources**

- **[1]** [Fine Tuning with Function Calling](https://docs.llamaindex.ai/en/stable/examples/finetuning/openai_fine_tuning_functions) — `0.749` —     # start_job_id="<start-job-id>"  # if you have an existing job, can specify id here     validate_json=False,  # openai validate json code doesn't support fu…
- **[2]** [Fine Tuning with Function Calling](https://docs.llamaindex.ai/en/stable/examples/finetuning/openai_fine_tuning_functions) — `0.745` — for idx, node in enumerate(nodes[:39]):     num_questions = 1  # change this number to increase number of nodes     dataset_generator = DatasetGenerator(       …
- **[3]** [Fine Tuning with Function Calling](https://docs.llamaindex.ai/en/stable/examples/finetuning/openai_fine_tuning_functions) — `0.740` — book import tqdm  for movie_name in tqdm(movie_names):     output = program(movie_name=movie_name)     print(output.json()) ```   ```python finetuning_handler.s…

In [10]:
show_answer(*model_routed_answer("Conceptually, how does LoRA differ from QLoRA?"))

[route: general] → course default


Based on the provided context excerpts, there is no mention or information regarding LoRA or QLoRA, so it is not possible to answer how they conceptually differ.

**Sources**

- **[1]** [YouTube audio integration](https://docs.langchain.com/oss/python/integrations/document_loaders/youtube_audio) — `0.661` —  sequence of hidden representations. On the other hand, a decoder is a component that takes in a sequence of hidden representations and generates a sequence of …
- **[2]** [YouTube audio integration](https://docs.langchain.com/oss/python/integrations/document_loaders/youtube_audio) — `0.624` — ains import RetrievalQA from langchain_community.vectorstores import FAISS from langchain_openai import ChatOpenAI, OpenAIEmbeddings from langchain_text_splitte…
- **[3]** [Embeddings](https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings) — `0.619` —         f"{description:<120}: Avg throughput: {sum(sentences_per_second) / len(sentences_per_second):.2f} queries/sec (over 5 runs)"     )   bench(baseline_mode…

**What just happened?** Both questions retrieved from the *same* knowledge base — the route changed only **who writes the answer**, which is a cost and quality decision, not a data one. This is the pattern behind "premium model for hard questions, cheap model for everything else" products; price the two branches with a dated table like the open-models lesson's and the routing threshold becomes an economic decision you can compute.

## 🔑 Key Takeaways

- **`tai-aitutor` is the code you already wrote.** From Section 9 on, notebooks import the pipeline instead of re-pasting it — every helper has the inline twin you built in Sections 3–7, and `??` shows it. What has *no* hand-built twin stays written out in the notebook, like the ingest loop above.
- **Load prebuilt stores; build small ones.** The 788-document corpus arrives pre-embedded with a manifest recording its build; the 23-article ai-docs set is cheap enough to embed live with the loop written out. Match the store to `EMBED_DIM`.
- **A router is one typed classification call plus `if`/`else`.** `route()` returns a validated `RouteDecision`; the dispatch is plain Python you can read, log, and test. No engine objects, no selector classes.
- **Validation is just a route.** A "reject" branch is the cheapest possible "no" — one classification call, no retrieval, no main-model tokens. Production moves the same rule into an agent's system prompt; Section 11 builds that agent.
- **Model routing** is the same pattern dispatching on `(provider, model)` — `generate()`'s per-call overrides make it a two-line branch.
- Route descriptions are tool descriptions: the model chooses by reading them. When a question mis-routes, fix the descriptions first.
- ⏭️ Next lesson: the conversation layer — memory as *the message list you choose to resend*, built by hand.